[2022-09-19 18:23:21,616] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-09-19T12:53:05.651457+00:00 [queued]>
[2022-09-19 18:23:21,625] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-09-19T12:53:05.651457+00:00 [queued]>
[2022-09-19 18:23:21,625] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 18:23:21,625] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-09-19 18:23:21,625] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 18:23:21,636] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-09-19 12:53:05.651457+00:00
[2022-09-19 18:23:21,639] {standard_task_runner.py:52} INFO - Started process 1569 to run task
[2022-09-19 18:23:21,641] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-09-19T12:53:05.651457+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/airflow.py', '--cfg-path', '/tmp/tmp4veb0xk4', '--error-file', '/tmp/tmp38two9x5']
[2022-09-19 18:23:21,642] {standard_task_runner.py:80} INFO - Job 13: Subtask inaccurate
[2022-09-19 18:23:21,679] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-09-19T12:53:05.651457+00:00 [running]> on host 0eef05c196e2
[2022-09-19 18:23:21,720] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T12:53:05.651457+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-19T12:53:05.651457+00:00
[2022-09-19 18:23:21,721] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-19 18:23:21,721] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-09-19 18:23:21,727] {subprocess.py:85} INFO - Output:
[2022-09-19 18:23:21,728] {subprocess.py:89} INFO - inaccurate
[2022-09-19 18:23:21,728] {subprocess.py:93} INFO - Command exited with return code 0
[2022-09-19 18:23:21,744] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220919T125305, start_date=20220919T125321, end_date=20220919T125321
[2022-09-19 18:23:21,773] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-19 18:23:21,791] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
