[2022-09-19 18:23:19,508] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-09-19T11:09:00+00:00 [queued]>
[2022-09-19 18:23:19,517] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-09-19T11:09:00+00:00 [queued]>
[2022-09-19 18:23:19,518] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 18:23:19,518] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-09-19 18:23:19,518] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 18:23:19,530] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-09-19 11:09:00+00:00
[2022-09-19 18:23:19,533] {standard_task_runner.py:52} INFO - Started process 1562 to run task
[2022-09-19 18:23:19,537] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-09-19T11:09:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/airflow.py', '--cfg-path', '/tmp/tmprgb0z65m', '--error-file', '/tmp/tmp0ln_hcfn']
[2022-09-19 18:23:19,537] {standard_task_runner.py:80} INFO - Job 12: Subtask inaccurate
[2022-09-19 18:23:19,579] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-09-19T11:09:00+00:00 [running]> on host 0eef05c196e2
[2022-09-19 18:23:19,617] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T11:09:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T11:09:00+00:00
[2022-09-19 18:23:19,618] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-19 18:23:19,618] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-09-19 18:23:19,625] {subprocess.py:85} INFO - Output:
[2022-09-19 18:23:19,627] {subprocess.py:89} INFO - inaccurate
[2022-09-19 18:23:19,627] {subprocess.py:93} INFO - Command exited with return code 0
[2022-09-19 18:23:19,644] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220919T110900, start_date=20220919T125319, end_date=20220919T125319
[2022-09-19 18:23:19,668] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-19 18:23:19,683] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
